### ISSUE TITLE
Creating certificate signing requests & Wildcards

### ISSUE THREAD

**Issue by ReinhardSchoeller** [ibm-cloud-docs/apps#18]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
use of wildcard in common name of csr is not supported

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/apps?topic=creating-apps-ssl_csr

3. Do you have a suggestion about how to resolve the issue?
Please include information in document to outline that wildcards are not supported

**Comment by christx83** [comment]
Thank you for pointing this out. This information will be added to the document in the next couple of days.
