### ISSUE TITLE
Add a new Step

### ISSUE THREAD

**Issue by ChuckCox** [ibm-cloud-docs/apps#25]
1. What are the details of the issue you're experiencing?  

I need to get a "Step 3" added to this tutorial (https://cloud.ibm.com/docs/ContinuousDelivery?topic=apps-tutorial-apps-devsecops). After the toolchain is created from Step 2, the user needs to make the following update to the "ci-pipeline" prior to running the pipeline:  
```
1. Open the toolchain in a browser
2. Click on the Delivery Pipeline tile called "ci-pipeline"
3. Click on the "Environment properties" menu on the left of the webpage
4. Click on the edit icon next to "vault-secret"
5. In the "Edit property" window click on the key icon
6. A "Secure property" pop-up window will appear and it will take a few seconds for the data to refresh with your Secrets Manager information. From the "Secret name" dropdown select "GPG_Key" and click OK
7. From the "Edit property" window click Save

After you have updated this value, you may safely run the pipeline.
```

2. Is this issue in reference to a specific page? If so, please provide a link.  

https://cloud.ibm.com/docs/ContinuousDelivery?topic=apps-tutorial-apps-devsecops

3. Do you have a suggestion about how to resolve the issue?  

Step 3 could be called "Step 3: Update Environment Properties Value", and instructions are above. 

![Screen Shot 2021-08-04 at 4 22 30 PM](https://user-images.githubusercontent.com/19801489/128375139-63f83ae8-8fe1-44a2-9287-fdfa83e534fa.png)

![Screen Shot 2021-08-05 at 10 16 49 AM](https://user-images.githubusercontent.com/19801489/128375341-292650a3-ec81-4f1f-a2e5-8cc0873378f5.png)

**Comment by christoc-ibm** [comment]
Closing this issue because I'm handling it in this doc issue:
https://github.ibm.com/Bluemix/docs/issues/8259 DevSecOps tutorial: Add step 3 for env property value
